Create SoftwareVersioning.md
betterscientificsoftware/bssw.io pull request #1061
Opened 2021-09-16 19:58 UTC by bernhold

Resolves #662

# Instructions (DELETE THIS SECTION)

To view these instructions, please hit the **Preview** tab (above left). After you have read all of these instructions, delete them entirely from the body of this issue before entering your submission.

Be sure to select `master` as the `base` branch above as the target for this PR.

Provide a general summary of your changes in the title above.

Fill in the below **Description** section with minimal text describing the changes/new contributions in this PR and replace `<...>` as appropriate.

Remove the beginning `` comment markers for the correct **checklist** to be used for this PR and delete the other checklist.  (The checklist items for files displayed on the bssw.io site are shown by default.  The checklist items for internal files not displayed in the bssw.io site is given below with commented out checklist items by default.)

Any checklist items that don't apply can be striked out by adding `~~` to the beginning and end of the checklist item as `* ~~[] <checklist-item>~~`.  Also, remove the strikeout markers `~~` for the [wikize_refs.py] checklist items if using formal citations for bssw.io contributions.

# Description

EB Member: @`<eb-member-id>`

Addresses issue #662

## PR checklist for files displayed on bssw.io site

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [ ] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

## PR checklist for (internal) files not displayed on bssw.io site

*Click "Write" above and remove comment markers to see below checklist items*

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

2021-09-20 14:41 UTC, bartlettroscoe commented
@bernhold, is this ready to review?

2021-09-20 14:44 UTC, bernhold commented
@bartlettroscoe yes, please

2021-09-23 13:34 UTC, bartlettroscoe requested changes
@bernhold, the article looks good.  I only see one small formatting issue.  I will put in a staggered PR to address it.

2021-09-23 13:34 UTC, bartlettroscoe commented on CuratedContent/SoftwareVersioning.md
> +Versioning is the process of assigning unique identifiers to instances of a product.
This newline shows up in both the GitHub rendering and the preview.bssw.io site as shown in the following screenshots:

![image](https://user-images.githubusercontent.com/1959736/134515782-f07b9e1a-dda4-4cba-9310-367e3cf012d8.png)

**On GitHub**

<br>

![image](https://user-images.githubusercontent.com/1959736/134515655-a899f28b-0bf6-4c23-bc39-fd0ac5e219d6.png)

**On preview.bssw.io**

<br>


It think we want to remove this newline.

2021-09-23 13:39 UTC, bartlettroscoe commented
@bernhold, I created the [stacked PR](https://preview.bssw.io/items/pull-request-size-matters#sfer-ezikiw-7) #1068 to fix the formatted issue.  Once that is merged against this PR branch, then this PR can be merged.

2021-09-23 13:43 UTC, bernhold commented
@bartlettroscoe thanks for the review and the correction.

@pagrubel will you have a chance to review soon?

2021-09-23 13:44 UTC, bartlettroscoe approved these changes
With the merge of PR #1068, the formatting is fixed as shown in the below GitHub screenshot.

![image](https://user-images.githubusercontent.com/1959736/134518171-7975cb34-b6a8-413d-9c05-007bcde5f46c.png)

I did not check preview.bssw.io but I would bet it is fixed there as well.

This is ready to be merged.

Thanks!

2021-09-23 13:45 UTC, bernhold commented
Sorry @bartlettroscoe  I inadvertently clicked to request a re-review.  Not necessary.

2021-09-23 13:50 UTC, bartlettroscoe commented
> Sorry @bartlettroscoe I inadvertently clicked to request a re-review. Not necessary.

@bernhold, no, that is appropriate to do when there is a posted "request changes" review on the PR and you want that reviewer to re-review the PR and sign off.

2021-09-30 17:59 UTC, rinkug approved these changes

2021-09-30 18:05 UTC, merged