Add first draft SSI guides
betterscientificsoftware/bssw.io pull request #1069
Opened 2021-09-23 15:46 UTC by pagrubel

# Instructions (DELETE THIS SECTION)

To view these instructions, please hit the **Preview** tab (above left). After you have read all of these instructions, delete them entirely from the body of this issue before entering your submission.

Be sure to select `master` as the `base` branch above as the target for this PR.

Provide a general summary of your changes in the title above.

Fill in the below **Description** section with minimal text describing the changes/new contributions in this PR and replace `<...>` as appropriate.

Remove the beginning `` comment markers for the correct **checklist** to be used for this PR and delete the other checklist.  (The checklist items for files displayed on the bssw.io site are shown by default.  The checklist items for internal files not displayed in the bssw.io site is given below with commented out checklist items by default.)

Any checklist items that don't apply can be striked out by adding `~~` to the beginning and end of the checklist item as `* ~~[] <checklist-item>~~`.  Also, remove the strikeout markers `~~` for the [wikize_refs.py] checklist items if using formal citations for bssw.io contributions.

# Description

EB Member: @`<eb-member-id>`

Resolves #`<issue-id>`

`<Other minimal information about the PR.>`

## PR checklist for files displayed on bssw.io site

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [ ] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [ ] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [ ] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [ ] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [ ] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [ ] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

## PR checklist for (internal) files not displayed on bssw.io site

*Click "Write" above and remove comment markers to see below checklist items*

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

2021-09-24 16:59 UTC, bartlettroscoe requested changes
@pagrubel, the article is nice and short and reads well.  I found only one issue that needs to be fixed before it is published.  I will post a stacked PR against this branch with a suggestion to fix.

2021-09-24 16:59 UTC, bartlettroscoe commented on CuratedContent/SoftwareSustainabilityInstituteGuides.md
> +Managers, researchers and developers can peruse a variety of topics such as building community, recruiting champions and students, managing research projects, data management plans and approaches to
> While researchers will find topics on publishing and the importance of openness in research helpful.

@pagrubel, I don't think that is a complete sentence.  I think you can make this a sentence by removing the word "While".

2021-09-24 17:03 UTC, bartlettroscoe commented on CuratedContent/SoftwareSustainabilityInstituteGuides.md
> +Managers, researchers and developers can peruse a variety of topics such as building community, recruiting champions and students, managing research projects, data management plans and approaches to
@pagrubel, the fix is in the [stacked PR](https://bssw.io/items/pull-request-size-matters#sfer-ezikiw-7) #1075.  That PR just needs to be accepted and merged to this PR branch and then this PR can be approved and merged.

2021-09-24 21:39 UTC, pagrubel commented
@bartlettroscoe Merged your fix, thanks.

2021-09-24 22:09 UTC, pagrubel commented
@bartlettroscoe I added a focus, let me know what you think

2021-09-24 22:28 UTC, pagrubel commented
@bartlettroscoe just waiting for your approval

2021-09-25 16:15 UTC, bartlettroscoe approved these changes
Looks good.  Thanks!

2021-09-27 18:08 UTC, pagrubel commented
@betterscientificsoftware/bssw-maint This PR is ready for final publication procedure.

2021-09-27 18:24 UTC, rinkug approved these changes

2021-09-27 18:25 UTC, merged

2021-09-27 19:15 UTC, rinkug commented
Published: https://bssw.io/items/software-sustainability-institute-guides