CC for "Getting an RSE org started" doc
betterscientificsoftware/bssw.io pull request #2037
Opened 2024-03-11 22:21 UTC by ksbeattie

Fill in the below **Description** section with minimal text describing the changes/new contributions in this PR and replace `<...>` as appropriate.

Any checklist items that do not apply can be striken out by adding `~~` to the beginning and end of the checklist item as `* ~~[] <checklist-item>~~`.
Also, remove the strikeout markers `~~` for the [wikize_refs.py] checklist items if using formal citations for bssw.io contributions.

# Description
My CC for the "Getting Started with the RSE Movement within your Organization: A Guide for Individuals" document [here](https://zenodo.org/records/10436166).

EB Member: @pagrubel 

Resolves #1999

## PR checklist for files displayed on bssw.io site

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [ ] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [ ] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [ ] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [ ] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [ ] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [ ] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

2024-03-25 17:33 UTC, pagrubel commented
@ksbeattie Do you have a draft for this?

2024-03-25 23:28 UTC, ksbeattie commented
> @ksbeattie Do you have a draft for this?

I do now, just updated this PR and took it out of draft.  Please review and provide feedback!

2024-03-27 22:15 UTC, pagrubel requested changes
@ksbeattie This looks good, I've requested some fixes to typos that can be incorporated.

2024-03-27 22:15 UTC, pagrubel commented on CuratedContent/GettingStartedWithAnRSEMovement.md
> +issues by providing practicle steps and tips for creating a local community of RSEs.  Starting with
```suggestion
issues by providing practical steps and tips for creating a local community of RSEs.  Starting with
```

2024-03-27 22:15 UTC, pagrubel commented on CuratedContent/GettingStartedWithAnRSEMovement.md
> +advocate for individluals to impact changes both at the personal and institutional level.
```suggestion
advocate for individuals to impact changes both at the personal and institutional level.
```

2024-03-27 22:15 UTC, pagrubel commented on CuratedContent/GettingStartedWithAnRSEMovement.md
> +Have you ever thought about starting an RSE movement within your university, lab or company?
```suggestion
Have you ever thought about starting an RSE movement within your university, lab, or company?
```

2024-03-27 22:15 UTC, pagrubel commented on CuratedContent/GettingStartedWithAnRSEMovement.md
> +how to raise awareness, creating spaces to participate together, recruting allies and formalizing
```suggestion
how to raise awareness, creating spaces to participate together, recruiting allies and formalizing
```

2024-03-27 22:25 UTC, pagrubel commented
@ksbeattie I went ahead and committed those small changes and the preview is rebuilding please check it and make sure it's ok for you. I'll approve when you are happy with it. I also put it on the content board.

2024-03-27 22:26 UTC, pagrubel approved these changes

2024-03-27 22:34 UTC, ksbeattie commented
I'm happy with all the spelling corrections - thank you!

2024-03-28 01:02 UTC, merged