Fix most markdownlint errors (#745)
betterscientificsoftware/bssw.io pull request #749
Opened 2021-03-23 21:25 UTC by bartlettroscoe

Here I fixed all but the errors for rules MD013, MD001, MD012, MD033 as per the proposed checks in #745.

I was able to filter these out with:

```
   $ markdownlint WorkingEffectivelyWithLegacyCode.md 2>&1 \
     | grep -v MD013 | grep -v MD001 | grep -v MD012 | grep -v MD033
```

and it comes back clean.

2021-03-23 21:33 UTC, markcmiller86 requested changes
- Apologies but #745 was not intended to *propose* specific lint rules to adopt or check. It was an examination of how an existing tool (in this case markdownlint-cli in NodeJS) *grades* our current content. 
- I captured [test results](https://github.com/betterscientificsoftware/bssw.io/pull/745#issuecomment-804480235) and opinions on what to do about them there
- We need to chat as a team about how to proceed with this.
- Until then, I think we should not modify any *existing* content.
- I recommend closing this for time being.

2021-03-23 21:37 UTC, bartlettroscoe commented
> I recommend closing this for time being.

All of the fixes are pretty clean so there is no reason not to merge this, regardless of what is decided in #745.

I guess the main purpose of this PR is to just preview the changes on the preview.bssw.io site before merging.  (Most people may have likely just merged to 'master' without even checking.)

2021-03-23 21:40 UTC, markcmiller86 commented
> All of the fixes are pretty clean so there is no reason not to merge this, regardless of what is decided in #745.

FWIW, I think it is best to wait until we've had group discussion before starting to go change any *existing* content. I just think that sets a poor precedent. So, if you're looking for an actual approval, you might want to assign someone other than me 😉

2021-03-23 21:41 UTC, bartlettroscoe commented
I updated the preview.bssw.io site and I inspected:

* https://preview.bssw.io/items/working-effectively-with-legacy-code

and it looks good from what I can see comparing to:

* https://bssw.io/items/working-effectively-with-legacy-code

(There look to be no changes in formatting and there should not be for the changes made in this PR.)

I will go ahead and merge.

2021-03-23 21:46 UTC, bartlettroscoe commented
> FWIW, I think it is best to wait until we've had group discussion before starting to go change any existing content.

@markcmiller86, okay, but I fear that little PRs like this will just drop into a blackhole and not get merged.

2021-03-23 21:50 UTC, markcmiller86 commented
> @markcmiller86, okay, but I fear that little PRs like this will just drop into a blackhole and not get merged.

Yeah but before you used the linter, you didn't even know this PR might have been needed and the *issues* it found have been there about as long as it takes to drop into a blackhole too.

2021-03-23 22:11 UTC, bartlettroscoe commented
> Yeah but before you used the linter, you didn't even know this PR might have been needed and the issues it found have been there about as long as it takes to drop into a blackhole too.

The same thing can be said for anyone's source code before upgrading to a new compiler or turning on more warnings.  It is always better to change code so that it produces less warnings when people run reasonable checks on them.  Just because a given interpreter/render/compiler is lenient for a given source file and does not emit warnings does not mean that the source file is 100% okay and will not cause problems in the future.

2021-03-24 00:54 UTC, markcmiller86 commented
> The same thing can be said for anyone's source code before upgrading to a new compiler or turning on more warnings.

And, when project teams decide to upgrade the compiler or turn on warnings, they *then* have to go fix them. We haven't decided that yet.

2021-06-17 11:48 UTC, rinkug commented
@markcmiller86 and @bartlettroscoe : This is sitting in item-review for sometime. What needs to be done with this?

2021-06-17 13:35 UTC, markcmiller86 commented
We delayed this pending resolution of #745. I need to circle back and adjust rules for linting there.

We have an opportunity to handle two separate decisions though...

1. Get markdown linting in place for *new* content only and leave existing content as is and only update upon *new* commits of existing content.
2. Go back and update *existing* content to pass whetever linting checks we put in place.

I suggest we get item 1 resolved asap and worry about 2 (and this PR) later.

2021-06-17 13:50 UTC, bartlettroscoe commented
> We have an opportunity to handle two separate decisions though

@markcmiller86, I vote for only applying linting to new and modified `*.md` files ASAP.  Then, if someone want so to go back and update all of the old content, then that can be a less urgent second stage.

2021-07-15 18:00 UTC, bartlettroscoe commented
We discussed this and decided this should be merged.  I will preview on preview.bssw.io and then merge.

2021-07-15 20:28 UTC, bartlettroscoe commented
I inspected the rendered file on:

* https://preview.bssw.io/items/working-effectively-with-legacy-code

and compared it to:

* https://bssw.io/items/working-effectively-with-legacy-code

for the lines changed in this PR and I can't observe any changes (which is good).

I think this is ready to merge (which I will do now).

2021-07-15 20:29 UTC, merged